# Generated by Django 5.1.1 on 2024-10-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
